<?php

namespace dk\SchoolManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoireRepository extends EntityRepository
{
}
