<?php

namespace dk\SchoolManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository
{
     public function findAllOrderedByTypepersonne()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM dkSchoolManagerBundle:Personne p ORDER BY p.typepersonne ASC'
            )
            ->getResult();
    }
}
