security:
    encoders:
        
        dk\SchoolManagerBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        main:
            id: fos_user.user_provider.username

    firewalls:
        #dev:
            #pattern:  ^/(_(profiler|wdt)|css|images|js)/
            #security: false
            
        # On crée un pare-feu uniquement pour le formulaire
        main_login:
        
            pattern:   ^/login$
            anonymous: true

        main:
            pattern:        ^/
            provider:       main
            form_login:
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /about
                use_referer : true
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                key:        %secret%    

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
